[build]
builder = "nixpacks"
buildCommand = "pip install -r requirements.txt"

[deploy]
startCommand = "python websocket_server.py"
restartPolicyType = "on-failure"
restartPolicyMaxRetries = 5

[variables]
PORT = "8081"
