[build]
builder = "nixpacks"
buildCommand = "python -m pip install --upgrade pip && python -m pip install -r requirements.txt"

[deploy]
startCommand = "python main.py"
restartPolicy = "always"

[variables]
PORT = "8080"
WEBSOCKET_PORT = "8081"
