[build]
builder = "nixpacks"
buildCommand = "pip install -r requirements.txt"

[deploy]
startCommand = "python websocket_server.py"
restartPolicy = "always"
numReplicas = 1

[variables]
PORT = "8081"
