services:
  - type: web
    name: encrypted-chat-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: SECRET_KEY
        generateValue: true
    disk:
      name: sqlite-data
      mountPath: /opt/render/project/src
      sizeGB: 1